### Основы Python и пакет NumPy
---


In [12]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [5]:
import numpy as np

In [6]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((1000,1000))
b = np.random.sample((1000,1000))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# тут можно писать код 
# ========
print(a)
print(b)

[[0.88813608 0.58405647 0.54984549 ... 0.49133362 0.53214195 0.22160656]
 [0.63057496 0.42864571 0.63061265 ... 0.33663295 0.24439627 0.43806451]
 [0.05227853 0.83188107 0.0484044  ... 0.30144557 0.06518118 0.29456285]
 ...
 [0.70642658 0.09064129 0.16968066 ... 0.65785088 0.45942383 0.60447321]
 [0.29701822 0.3291712  0.56701028 ... 0.22847039 0.10833673 0.26944381]
 [0.84155552 0.32359672 0.65246636 ... 0.4222556  0.27814528 0.65847845]]
[[0.04348208 0.53550652 0.67868104 ... 0.55316012 0.63864354 0.94740979]
 [0.9651733  0.45270491 0.4552069  ... 0.26604622 0.30400639 0.82128162]
 [0.87921044 0.01626053 0.06015716 ... 0.52115968 0.0827743  0.9111334 ]
 ...
 [0.16054254 0.32678121 0.49302787 ... 0.4322927  0.78308548 0.9796925 ]
 [0.34231673 0.72267515 0.95108915 ... 0.28629708 0.51177658 0.74124502]
 [0.62926494 0.71243486 0.77267195 ... 0.98831625 0.88601435 0.95481306]]


In [1]:
def mult(a, b):
    t = []
    c = []
    result = 0
    for i in range(0,999):
        for j in range(0,999):
            for k in range(0,999):
                result += a[i][k] * b[k][j]
            t.append(result)
            result = 0
            c.append(t)
            t = []
        return c

In [2]:
def np_mult(a, b):
    return a @ b

In [7]:
%%time
# засечем время работы функции без NumPy
mult(a,b)

Wall time: 872 ms


[[236.2512654277466],
 [245.41499979652258],
 [249.4737612495477],
 [245.99284009221768],
 [254.01398322761693],
 [248.3619589206409],
 [245.9051948252811],
 [246.98896791928962],
 [244.04159899956238],
 [245.3104160112856],
 [248.49209082634945],
 [253.00517760144538],
 [240.35383017975224],
 [242.35018016858004],
 [254.55217802127035],
 [250.4374514228636],
 [240.7712644218432],
 [242.39158114711458],
 [243.56798697653207],
 [253.24764503586107],
 [252.4072684973304],
 [242.96679648958062],
 [250.21438032346333],
 [247.92466336600552],
 [244.77025422193606],
 [244.79736333748838],
 [248.42745835060992],
 [248.56892105462873],
 [247.79966932869485],
 [255.3477570693686],
 [244.13522096376946],
 [253.08553112945688],
 [246.11589478730048],
 [248.67192361977283],
 [261.69961022930545],
 [246.61546755732215],
 [248.91613201204342],
 [249.7940676033287],
 [250.66519066615945],
 [247.56750258245637],
 [246.55790597505265],
 [241.908907383636],
 [246.31649882810427],
 [242.74934444593293],


In [8]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

Wall time: 149 ms


array([[236.39071467, 245.57288003, 249.64499042, ..., 248.84240785,
        244.82781133, 251.92476895],
       [246.0925203 , 248.67667443, 255.50251151, ..., 261.41820398,
        253.18371404, 253.14765092],
       [246.51407119, 251.29293153, 251.81975471, ..., 261.43535062,
        249.18173255, 256.73441453],
       ...,
       [230.28275712, 238.45918226, 238.194537  , ..., 246.64123253,
        242.66006022, 245.54703325],
       [240.98287781, 243.82474923, 254.26899088, ..., 248.41637873,
        246.88597961, 249.11343756],
       [238.38262553, 246.33821105, 252.76921462, ..., 255.32215388,
        254.94509353, 252.67929321]])

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [9]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return A.sum()/len(A)

In [10]:
# функция без NumPy
def stupid_sec_av(A):
    summa = 0
    for i in range(len(A)):
        summa = summa = A[i]
    return summa/len(A)

In [13]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 7) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 22.1 ms
Wall time: 1.47 s


0.5000103864758288

### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке. 

In [18]:
# функция, решающая задачу с помощью NumPy
# отразить элементы матрицы в обратном порядке a[::-1]
def transformation(X, a=1):
    Y = X.copy()
    if a is None:
        Y[1:len(X):2] = 1
    else:
        Y[1:len(X):2] = a
    temp = []
    temp = Y[0:len(X):2].copy()
    temp = temp ** 3
    temp[::-1]
    
    return Y

In [40]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a = 1):
    Y = []
    for element in X:
        Y.append(element)
    print(Y)
    temp = []
    for i in range(0,len(Y)):
        if i % 2 == 0:
            Y[i] = Y[i] ** 3
            temp.append(Y[i])
        else:
            if a is None:
                Y[i] = 1
            else:
                Y[i] = a
    print(Y)
    temp.reverse()
    k = 0
    for i in range(0,len(Y)):
        if i % 2 == 0:
            Y[i] = temp[k]
            k += 1
    for element in X:
        Y.append(element)
    Y.reverse
    return Y

In [30]:
X = sps.uniform.rvs(size=10 ** 1) 
print(X)
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
Y = transformation(X)
print(Y)

[0.76058563 0.65402692 0.71464912 0.45411791 0.06382446 0.42987551
 0.84256246 0.1173464  0.61586746 0.43420311]
Wall time: 0 ns
[0.76058563 1.         0.71464912 1.         0.06382446 1.
 0.84256246 1.         0.61586746 1.        ]


In [41]:
X = sps.uniform.rvs(size=10 ** 1) 
print(X)
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
#%time S1 = stupid_transformation(X)
Y = stupid_transformation(X)
print(Y)

[0.78647691 0.22147501 0.24014557 0.36040876 0.9406045  0.6415608
 0.28282565 0.86029351 0.05025237 0.92263199]
[0.7864769147281991, 0.22147500694118616, 0.2401455707039738, 0.36040876333179717, 0.9406044986680228, 0.6415607980097663, 0.28282564882458905, 0.8602935078341878, 0.05025237400396898, 0.9226319944962373]
[0.48647210046431816, 1, 0.013849169878128932, 1, 0.8321874357706536, 1, 0.022623321969021733, 1, 0.0001269023749998153, 1]
[0.0001269023749998153, 1, 0.022623321969021733, 1, 0.8321874357706536, 1, 0.013849169878128932, 1, 0.48647210046431816, 1, 0.7864769147281991, 0.22147500694118616, 0.2401455707039738, 0.36040876333179717, 0.9406044986680228, 0.6415607980097663, 0.28282564882458905, 0.8602935078341878, 0.05025237400396898, 0.9226319944962373]


Почему методы ***numpy*** оказываются эффективнее?

In [ ]:
# Ваш ответ

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать.  

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [ ]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш код здесь

draw_f(gridx, gridy)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
path_to_image = './image.png'
image_array = plt.imread(path_to_image)
plt.imshow(image_array);

In [ ]:
flat_image_array = # Ваш код здесь

In [ ]:
# здесь выведите размер нового массива